### PR TITLE
Closes #53: Wysiwyg links

### LINKED ISSUE #53: Wysiwyg links
Links are displayed as HTML in calendar events.

<bountysource-plugin>

---

Want to back this issue? **[Place a bounty on it!](https://www.bountysource.com/issues/1381326-wysiwyg-links?utm_campaign=plugin&utm_content=tracker%2F424454&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F424454&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by marcosgdf**
Improved `dol_textishtml` function.

Now it takes less memory and does a better HTML detection 

Before:

```
Total Incl. Wall Time (microsec):   134 microsecs
Total Incl. CPU (microsecs):    0 microsecs
Total Incl. MemUse (bytes): 4,072 bytes
Total Incl. PeakMemUse (bytes): 0 bytes
Number of Function Calls:   17
```

After:

```
Total Incl. Wall Time (microsec):   42 microsecs
Total Incl. CPU (microsecs):    0 microsecs
Total Incl. MemUse (bytes): 3,992 bytes
Total Incl. PeakMemUse (bytes): 0 bytes
Number of Function Calls:   4
```

### CODE REVIEW

**Comment by marcosgdf** [comment]
Seems Scrutinizer errored. Not related with this PR though

**Comment by rdoursenaud** [comment]
I don't think we need that on our repo. Upstream seems enough to me.

**Comment by marcosgdf** [comment]
Jean-Pierre once told me that contributions to Dolibarr must show that they were "sponsored/funded" by GPC, and so I make a PR to your fork and you do a PR to main dolibarr repo.

Should I push upstream then instead of here?

**Comment by rdoursenaud** [comment]
Yes please. That was stupid of me to ask for more work ;)

**Pull request closed without merging**
